language: python
python:
  - "3.5"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
# command to run tests
script: coverage run test_rpn.py
after_success:
  - coverage report --omit '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/*'
  - coveralls
  