language: python
python:
  - "3.5"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install colored
# command to run tests
script: coverage run --omit '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/*' test_rpn.py
after_success:
  - coverage report
  - coveralls
